### ISSUE TITLE
Denying ping perms still allows @everyone and @here to be pinged

### ISSUE THREAD

**Issue by yitzy299** [MinnDevelopment/discord-webhooks#35] opened 2021-06-16 05:35 UTC
`builder.setAllowedMentions(AllowedMentions.none().withParseUsers(true));`

This denies user mention perms, but does not disable @everyone and @here

**Comment by MinnDevelopment** [comment] 2021-06-16 08:58
```kotlin
val mentions = AllowedMentions.none().withParseUsers(true)

client.send(
    WebhookMessageBuilder()
        .setAllowedMentions(mentions)
        .setContent("@everyone")
        .build()
)
client.send(
    WebhookMessageBuilder()
        .setAllowedMentions(mentions)
        .setContent("@here")
        .build()
)
client.send(
    WebhookMessageBuilder()
        .setAllowedMentions(mentions)
        .setContent("<@86699011792191488>")
        .build()
)
client.send(
    WebhookMessageBuilder()
        .setAllowedMentions(mentions)
        .setContent("<@&708018860359417907>")
        .build()
)
```

![image](https://user-images.githubusercontent.com/18090140/122190021-b9570600-ce91-11eb-9353-7b44622939dd.png)

**Comment by MinnDevelopment** [comment] 2021-07-15 13:32
Closing this since I cannot reproduce this.

**Closed by MinnDevelopment** 2021-07-15 13:32 UTC
