### ISSUE TITLE
Error in Sending Webhooks

### ISSUE THREAD

**Issue by G-Kumaran** [MinnDevelopment/discord-webhooks#11] opened 2020-07-25 15:01 UTC
Version :
```xml
<dependency>
    <groupId>club.minnced</groupId>
    <artifactId>discord-webhooks</artifactId>
    <version>0.3.2</version>
</dependency>
```

Environment:
Java 8 with SpringBoot

Code:
```java
WebhookClient.withUrl("https://discordapp.com/api/webhooks/736596600071127061/[REDACTED]")
     .send("Test");
```

Error:
```
ERROR 20760 --- [596600071127061] c.minnced.discord.webhook.WebhookClient  : Sending a webhook message failed with non-OK http response

club.minnced.discord.webhook.exception.HttpException: Request returned failure 400: {"code": 50035, "errors": {"allowed_mentions": {"_errors": [{"code": "MODEL_TYPE_CONVERT", "message": "Only dictionaries may be used in a ModelType"}]}}, "message": "Invalid Form Body"}
	at club.minnced.discord.webhook.WebhookClient.failure(WebhookClient.java:375) [discord-webhooks-0.3.2.jar:na]
	at club.minnced.discord.webhook.WebhookClient.executePair(WebhookClient.java:438) [discord-webhooks-0.3.2.jar:na]
	at club.minnced.discord.webhook.WebhookClient.drainQueue(WebhookClient.java:411) [discord-webhooks-0.3.2.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_252]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_252]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) ~[na:1.8.0_252]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) ~[na:1.8.0_252]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_252]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_252]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_252]
```

**Comment by MinnDevelopment** [comment] 2020-07-25 15:13
I'm unable to reproduce this with your provided code.

**Comment by G-Kumaran** [comment] 2020-07-25 15:15
Yeah i received your ping. 
But i can consistently reproduce this issue in my code.
Any more debugging info that i can provide to assist you?

**Comment by G-Kumaran** [comment] 2020-07-25 15:18
To test Ive manually created a webhook without this api and yet i still get this issue. 
So I'm guessing issue isn't in the api...

Damn

**Comment by MinnDevelopment** [comment] 2020-07-25 15:27
Potentially this is an issue with your dependencies which somehow conflict with the JSON library?

**Comment by G-Kumaran** [comment] 2020-07-25 15:46
You could be right, created a new project with only just the spring-boot-starter and the discord-webhooks dependancies without the any other dependancies. Webhooks now pass.
What json library is discord-webhooks api using? Im on Jackson.

**Comment by MinnDevelopment** [comment] 2020-07-25 17:20
This library uses [`org.json:json:20180813`](https://github.com/stleary/JSON-java/)

**Comment by kantenkugel** [comment] 2020-07-25 17:35
Jackson shouldn't conflict with org.json though. More likely some of your other dependencies relies on a different version of org.json

**Comment by G-Kumaran** [comment] 2020-07-25 17:40
After hours of combination and errors, not able to identify the actual issue.

But found the cause of issue.
```code
<dependency>
	<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-starter-test</artifactId>
	<scope>test</scope>
</dependency>
```
Addin this to the pom causes the issue, deleting this from the pom and webhook passes.

Can u reproduce the issue based on this?

**Comment by MinnDevelopment** [comment] 2020-07-25 18:06
I don't use maven and have no maven setup but I assume the reason is that maven resolves dependencies on first sight rathar than using the latest. The issue might be solved by putting this library as your first dependency.

**Comment by G-Kumaran** [comment] 2020-07-25 18:10
Update :
Analysis of packages inside the sping-boot-starter-boot:
This package is causing the issue.
```code
<groupId>org.skyscreamer</groupId>
<artifactId>jsonassert</artifactId>
```
Source : https://github.com/skyscreamer/JSONassert
Im guessing somthing in this breaks the discord api.

Quick note, this is included in the default https://start.spring.io config.

**Comment by MinnDevelopment** [comment] 2020-07-25 18:24
It's likely that some dependency causes a different version of the `org.json.JSONObject` class to load which can't handle the `JSONString` interface correctly.

**Comment by kantenkugel** [comment] 2020-07-25 20:09
Well i think this issue explains it pretty well: https://github.com/spring-projects/spring-boot/issues/8706

**Comment by MinnDevelopment** [comment] 2020-07-25 20:40
Then the solution is to exclude this android re-implementation. Closing as resolved.

**Closed by MinnDevelopment** 2020-07-25 20:40 UTC

**Comment by G-Kumaran** [comment] 2020-07-25 20:49
Thanks for the explanation @kantenkugel
