### ISSUE TITLE
Using Components

### ISSUE THREAD

**Issue by thauanvargas** [MinnDevelopment/discord-webhooks#89] opened 2023-09-23 21:41 UTC
Hello I've just started using this library, but I don't find anyway of adding Components to the webhook message, is this possible?

I need to add a button to the last sent webhook message, patching last one if it was sent before.

**Comment by MinnDevelopment** [comment] 2023-09-24 10:43
Components can only be used by bots and application owned webhooks. However, there is a PR to support them in those cases #73

**Comment by MinnDevelopment** [comment] 2023-09-25 11:05
Closing as duplicate of #46

**Closed by MinnDevelopment** 2023-09-25 11:05 UTC
